anchor_version = "0.23.0"

[provider]
cluster = "devnet"
wallet = "scripts/cc-draffle-deploy-keypair.json"

[programs.devnet]
draffle = "5tA54UMYd1tBSJ2VTaUBFE7mWZsM3n1pPucMyzvguQU1"

[scripts]
test = "mocha -t 1000000 tests"